import uuid
import logging
from pathlib import Path
from urllib.parse import quote

import qrcode
from feedgen.feed import FeedGenerator

from django.conf import settings
from django.utils import timezone

from core.utils import get_timezone_aware_datetime
from .utils import generate_artwork_img
from .models import Feed

logger = logging.getLogger(__name__)


def has_audio_files(directory):
    # .rglob('*') looks through all subfolders recursively
    for file in directory.rglob('*'):
        if (
            file.is_file()
            and file.suffix.lower().lstrip(".") in settings.AUDIO_EXTENSIONS
        ):
            return True
    return False

def get_audio_files(directory):
    # Changed to .rglob('*') to find files in nested folders
    audio_files = [
        f
        for f in Path(directory).rglob('*')
        if f.is_file() and f.suffix.lower().lstrip(".") in settings.AUDIO_EXTENSIONS
    ]
    return audio_files

def scan_library_for_subdirs():
    root = Path(settings.LIBRARY_ROOT)
    # This keeps the "Top Level" folders as the primary feeds in your dashboard
    dirs = [d for d in root.iterdir() if d.is_dir() and has_audio_files(d)]
    return dirs

def generate_feed_url_qr_code(url, directory):
    qr_path = directory.resolve() / "feed_qr_code.png"

    qr = qrcode.QRCode(
        version=1,
        error_correction=qrcode.constants.ERROR_CORRECT_L,
        box_size=8,
        border=2,
    )
    qr.add_data(url)
    qr.make(fit=True)

    img = qr.make_image(fill_color="black", back_color="white")
    img.save(qr_path)

    logger.info(f"Successfully generated QR code for feed folder {directory.name}")

    return qr_path


def get_artwork_url(request_host, directory, title_text):
    artwork_name = "artwork.png"
    artwork_path = directory / artwork_name

    if not artwork_path.exists() or not artwork_path.is_file():
        generate_artwork_img(title_text, artwork_path)

    return f"http://{request_host}/{settings.LIBRARY_URL}{quote(directory.name)}/{artwork_name}"


class FeedItem:
    def __init__(self, request_host, dir_name, file, feed_generator):
        self.creation_timestamp = file.stat().st_ctime
        self.episode = feed_generator.add_entry()

        # Logic to append folder names to the title for recursive files
        # It calculates the path relative to the main feed folder
        relative_path = file.relative_to(Path(settings.LIBRARY_ROOT) / dir_name)
        if len(relative_path.parts) > 1:
            # Result: "Subfolder - File"
            display_title = " - ".join(list(relative_path.parent.parts) + [file.stem])
        else:
            display_title = file.stem

        self.episode.title(display_title)
        self.episode.author(
            {"name": settings.ADMINS[0][0], "email": settings.ADMINS[0][1]}
        )
        self.episode.description(
            f"a podcast episode auto-generated by FolderCast from '{dir_name}' directory."
        )
        self.episode.pubDate(get_timezone_aware_datetime(self.creation_timestamp))
        
        # URL construction remains the same to ensure Nginx can find the file
        file_url_path = quote(str(relative_path))
        self.episode.enclosure(
            url=f"http://{request_host}/{settings.LIBRARY_URL}{quote(dir_name)}/{file_url_path}",
            type=settings.AUDIO_MIME_TYPES.get(
                file.suffix.lower().lstrip("."), "audio/mpeg"
            ),
            length=str(file.stat().st_size),
        )

class FeedGeneratorService:
    """
    Generate an RSS feed from a directory of audio files.
    Returns feed's metadata.
    """

    def __init__(self, request_host, directory, audio_files):
        self.request_host = request_host
        self.directory = directory
        self.feedgen = FeedGenerator()
        self.audio_files = audio_files

    def setup(self):
        fg = self.feedgen
        fg.id(uuid.uuid4())
        fg.title(f"TadCast: {self.directory.name}")
        fg.author({"name": settings.ADMINS[0][0], "email": settings.ADMINS[0][1]})
        fg.logo(get_artwork_url(self.request_host, self.directory, self.directory.name))
        fg.subtitle(
            f"{self.directory.name}"
        )
        fg.language("en")
        fg.link(
            href=f"http://{self.request_host}/{settings.LIBRARY_URL}{quote(self.directory.name)}/feed.rss",
            rel="self",
        )
        fg.ttl(60)
    def add_episodes(self):
        if not self.audio_files:
            logger.warning(f"No files found in folder: {self.directory.name}")
            return

        for file in self.audio_files:
            FeedItem(
                request_host=self.request_host,
                dir_name=self.directory.name,
                file=file,
                feed_generator=self.feedgen,
            )

    def write_feed(self):
        rss_file = Path(
            settings.LIBRARY_ROOT,
            self.directory.name,
            "feed.rss",
        )
        rss_file.parent.mkdir(parents=True, exist_ok=True)
        self.feedgen.rss_file(str(rss_file), pretty=True)

        rss_url = f"http://{self.request_host}/{settings.LIBRARY_URL}{quote(self.directory.name)}/feed.rss"

        logger.info(f"Successfully written feed {self.directory.name} to file.")

        return rss_url

    def generate_qr(self, rss_url):
        return generate_feed_url_qr_code(url=rss_url, directory=self.directory)

    def save(self, rss_url):
        feed_metadata = {
            "name": self.directory.name,
            "url": rss_url,
            "items_count": len(self.audio_files),
            "artwork": self.feedgen.logo(),
            "qr_code": f"http://{self.request_host}/{settings.LIBRARY_URL}{quote(self.directory.name)}/feed_qr_code.png",
            "last_generated": timezone.now(),
        }
        feed, created = Feed.objects.update_or_create(
            name=self.directory.name, defaults=feed_metadata
        )
        action = "created" if created else "updated"
        logger.info(f"{feed.name} successfully {action} in the database.")

        return feed

    def build(self):
        self.setup()
        self.add_episodes()

        rss_url = self.write_feed()
        self.generate_qr(rss_url)

        feed = self.save(rss_url)

        logger.info(f"Successfully generated feed for {self.directory.name}")

        return feed


def generate_feed(request_host, directory):
    audio_files = get_audio_files(directory)
    if not audio_files:
        return None

    service = FeedGeneratorService(request_host, directory, audio_files)
    return service.build()
